#!/usr/bin/env bash
# scripts/extract_agent1a_stream.sh — Extract Agent 1a artifacts from a stream-json JSONL file.
#
# Usage:
#   extract_agent1a_stream.sh \
#     <stream_file>        # agent1a_output.txt.stream (JSONL, one event per line)
#     <output_txt>         # agent1a_output.txt        (assistant text only)
#     <evidence_txt>       # agent1a_evidence.txt      (text + tool calls + tool results + result meta)
#     <meta_env>           # agent1a_meta.env          (session_id, stop_reason, result_subtype, exit_code)
#     <exit_code>          # exit code from the claude invocation (integer)
#
# All outputs are always written, even if stream is empty or malformed.
# Uses jq -Rr 'fromjson?' so non-JSON lines are silently skipped.
# Large tool results are clipped at TOOL_RESULT_MAX_BYTES (default 4096).
# Stderr must not be mixed into the stream file — caller must redirect separately.
set -Eeuo pipefail
IFS=$'\n\t'

_STREAM_FILE="${1:-}"
_OUTPUT_TXT="${2:-}"
_EVIDENCE_TXT="${3:-}"
_META_ENV="${4:-}"
_EXIT_CODE="${5:-0}"

TOOL_RESULT_MAX_BYTES="${TOOL_RESULT_MAX_BYTES:-4096}"

# Validate required args
if [ -z "$_STREAM_FILE" ] || [ -z "$_OUTPUT_TXT" ] || [ -z "$_EVIDENCE_TXT" ] || [ -z "$_META_ENV" ]; then
  printf 'extract_agent1a_stream.sh: missing required arguments\n' >&2
  printf 'Usage: %s <stream> <output_txt> <evidence_txt> <meta_env> [exit_code]\n' "$0" >&2
  exit 1
fi

# Ensure stream file exists (may be empty)
touch "$_STREAM_FILE" 2>/dev/null || true

# --- Extract assistant text ---
# Only text-type content blocks from assistant messages.
jq -Rr '
  fromjson?
  | select(.type == "assistant")
  | .message.content[]?
  | select(.type == "text")
  | .text
' "$_STREAM_FILE" 2>/dev/null > "$_OUTPUT_TXT" || true

# Ensure file exists even if jq produced nothing
touch "$_OUTPUT_TXT" 2>/dev/null || true

# --- Extract evidence transcript ---
# Includes: assistant text blocks, tool call summaries, tool results (clipped), result metadata.
{
  printf '# Agent 1a Evidence Transcript\n'
  printf '# Generated by extract_agent1a_stream.sh\n\n'

  jq -Rr --argjson clip "$TOOL_RESULT_MAX_BYTES" '
    fromjson?
    | if .type == "assistant" then
        .message.content[]?
        | if .type == "text" then
            "ASSISTANT_TEXT: " + .text
          elif .type == "tool_use" then
            "TOOL_CALL: " + .name + "(" + (.input | tojson) + ")"
          elif .type == "thinking" then
            "ASSISTANT_THINKING: " + .thinking
          else empty end

      elif .type == "tool" then
        .content[]?
        | if .type == "tool_result" then
            "TOOL_RESULT [id=" + (.tool_use_id // "?") + "]: " +
            (if (.content | type) == "string" then
               if (.content | length) > $clip then
                 (.content[:$clip]) + "\n... [clipped " + ((.content | length - $clip) | tostring) + " bytes]"
               else .content end
             elif (.content | type) == "array" then
               (.content[]? | if .type == "text" then
                  if (.text | length) > $clip then
                    (.text[:$clip]) + "\n... [clipped " + ((.text | length - $clip) | tostring) + " bytes]"
                  else .text end
                else empty end)
             else (.content | tojson) end)
          else empty end

      elif .type == "result" then
        "RUN_RESULT: stop_reason=" + (.stop_reason // "unknown") +
        " subtype=" + (.result_subtype // "none") +
        " duration_ms=" + ((.duration_ms // 0) | tostring) +
        " cost_usd=" + ((.cost_usd // 0) | tostring)

      else empty end
  ' "$_STREAM_FILE" 2>/dev/null || true
} > "$_EVIDENCE_TXT" || true

# Ensure file exists
touch "$_EVIDENCE_TXT" 2>/dev/null || true

# --- Extract metadata ---
_SESSION_ID="$(jq -Rr 'fromjson? | select(.type == "system") | .session_id // empty' \
  "$_STREAM_FILE" 2>/dev/null | head -1 || true)"
_STOP_REASON="$(jq -Rr 'fromjson? | select(.type == "result") | .stop_reason // empty' \
  "$_STREAM_FILE" 2>/dev/null | head -1 || true)"
_RESULT_SUBTYPE="$(jq -Rr 'fromjson? | select(.type == "result") | .result_subtype // empty' \
  "$_STREAM_FILE" 2>/dev/null | head -1 || true)"

{
  printf 'session_id=%s\n'       "${_SESSION_ID:-}"
  printf 'stop_reason=%s\n'      "${_STOP_REASON:-}"
  printf 'result_subtype=%s\n'   "${_RESULT_SUBTYPE:-}"
  printf 'exit_code=%s\n'        "${_EXIT_CODE:-0}"
} > "$_META_ENV" || true

# Ensure file exists
touch "$_META_ENV" 2>/dev/null || true
